const DEFAULT_SEPARATOR_CLASSNAME = "_separator shrink-0 border-none bg-mode-accent"

const SEPARATOR_HORIZONTAL_CLASSNAME = "h-[1px] w-full"

const SEPARATOR_VERTICAL_CLASSNAME = "w-[1px] h-full"

export { DEFAULT_SEPARATOR_CLASSNAME, SEPARATOR_HORIZONTAL_CLASSNAME, SEPARATOR_VERTICAL_CLASSNAME }
